### ISSUE TITLE
Run Xcode Test Plans

### ISSUE THREAD

**Issue by Sparklydust** [sersoft-gmbh/xcodebuild-action#10]
I would like to be able to run my Test Plans instead of the traditional tests. Is it possible to achieve this with this GitHub actions repository?

**Comment by Sparklydust** [comment]
No problem. 
I have found this [article about xctestplan](https://useyourloaf.com/blog/xcode-test-plans/) that would give you a sum up of what it is exactly and at the end of it, there is command line to run the tests from Terminal. Maybe it could help you out, what do you think?

**Comment by ffried** [comment]
@Sparklydust Thanks! It's not possible right now, but with #11 it should be. As soon as everything works as expected, I'll release a new version.
