### ISSUE TITLE
Add support for xcbeautify

### ISSUE THREAD

**Issue by pronebird** [sersoft-gmbh/xcodebuild-action#152]
Hi,

I found that xcpretty does not really pick up the output from Xcode test plans running in parallel but xcbeautify works fine. It would be great to add an option to use `xcbeautify`. I think it works the same way as xcpretty, i.e the output is piped through.

**Comment by ffried** [comment]
I've just made the output formatting more flexible. A new `output-formatter` input supersedes the `use-xcpretty` inputs. You can specify any formatting tool here - as long as it's a command line tool that takes the `xcodebuild` output to stdin from a pipe.

**Comment by pronebird** [comment]
@ffried amazing! Thank you so much!
