### ISSUE TITLE
support for -archivePath

### ISSUE THREAD

**Issue by sjo-regin** [sersoft-gmbh/xcodebuild-action#174]
Would be great to have support for xcodebuild **-archivePath**
Inspiration can be found in https://github.com/sergeysova/xcodebuild-action

**Comment by ffried** [comment]
Fixed in [v3.2.0](https://github.com/sersoft-gmbh/xcodebuild-action/releases/tag/v3.2.0)

**Comment by sjo-regin** [comment]
> Fixed with [4d9f5ce](https://github.com/sersoft-gmbh/xcodebuild-action/commit/4d9f5cef318c7592694b188de7fe0f367802ba34) in [v3.2.0](https://github.com/sersoft-gmbh/xcodebuild-action/releases/tag/v3.2.0)

It is working, thank you!
