### ISSUE TITLE
Log xcodebuild command before execution

### ISSUE THREAD

**Issue by paulz** [sersoft-gmbh/xcodebuild-action#27]
Thank you for the great GitHub action!
We use it everyday on GitHub and self hosted runners.

Sometime we have to reproduce the failure locally and it's hard to construct exact command that caused the failure.
It would be great if action logs `xcodebuild` command before executing it. This way when build has failed on CI, we can copy paste it locally in attempt to reproduce the failure.

We used to do that when we simply run `xcodebuild` as a shell command from our workflow. Now we use action it takes time to convert action parameters to `xcodebuild` parameters.

**Comment by ffried** [comment]
I've just released [v1.5.0](https://github.com/sersoft-gmbh/xcodebuild-action/releases/tag/v1.5.0) which does exactly that 😉 
Note that you can also get hold of the executed command in the now publicly available output `executed-command`.

**Comment by paulz** [comment]
Thank you so much @ffried ! Will try it today.

**Comment by paulz** [comment]
works great, many thanks!
