### ISSUE TITLE
Feature: Colorized Output

### ISSUE THREAD

**Issue by paulz** [sersoft-gmbh/xcodebuild-action#36]
Thank you for useful action!

Would it be possible to allow color output in logs?

`xcpretty --color`

https://github.blog/2020-09-23-a-better-logs-experience-with-github-actions/#opening-the-door-to-a-more-colorful-experience

**Comment by ffried** [comment]
Just published [v1.7.0](https://github.com/sersoft-gmbh/xcodebuild-action/releases/tag/v1.7.0) which enables colored output by default. Also, a new input `xcpretty-colored-output` is available to disable coloring if needed.
